
logging:
  level:
    root: INFO
  charset:
    console: UTF-8
  file:
    name: "my.log"
    path: "./logs/"

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"


swagger2:
  enable: true

#oss:
#  endpoint: "oss-accelerate.aliyuncs.com"
#  accessKeyId: "LTAI5tLw5TZCi1zoNJJ2Z6uY"
#  accessKeySecret: "MOTEWvkRKIjiSNOGRKs3FhsSY0jTXF"
#  buckName: "works-oss"

server:
  port: 8082

dubbo:
  application:
    name: works-webs
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry